version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
    ports:
      - 3000:3000

  db:
    image: mongo:5
    ports:
      - 27017:27017
