version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
    ports:
      - 4000:4000

  db:
    image: mongo:5
    ports:
      - 27017:27017
