version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/polar-scene-370203/my-backend:1.4
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    env_file:
      - ./.env.prod
    ports:
      - 3000:3000
